### ISSUE TITLE
help，copy Failed

### ISSUE THREAD

**Issue by adangran** [chemodax/pbench#2]
![image](https://github.com/chemodax/pbench/assets/39615236/96f13ca4-3c17-4f4a-8d62-f112895839e8)

why?

**Comment by chemodax** [comment]
This happens because there is no such executable `copy`: copy is command processed by cmd.exe. Use the following command to measure copy command:
```
### pbench.exe cmd.exe /c copy DCIM.zip m:\files
```

**Comment by adangran** [comment]
> This happens because there is no such executable `copy`: copy is command processed by cmd.exe. Use the following command to measure copy command:
> 
> ```
> ### pbench.exe cmd.exe /c copy DCIM.zip m:\files
> ```

Thank you!
